import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Analytics } from "@vercel/analytics/react";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/home/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MadeEasy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <Analytics />
          <Toaster />
          <main className=" m-auto overflow-hidden">
            <Header />
            <main className="py-16 px-2 md">{children}</main>
            <Footer />
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
